Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -20,7 +20,8 @@ commands:
       - run:
           name: Checking environment variables and parameters
           environment:
-            SKIP: << parameters.skip-build-on-targets >>
+            SKIP: "<<parameters.skip-build-on-targets>>"
+            CENTRAL_CONFIG: "<<parameters.config-to-deploy>>"
           command: |
             CheckEnvVars() {
                         if [ -z "${GH_TOKEN:-}" ]; then
@@ -29,9 +30,17 @@ commands:
                             exit 1
                         fi
             }
-            
+
+            NotThisConfig() {
+                        if [ $(git hash-object ${CENTRAL_CONFIG}) = $(git hash-object $HOME/.circleci/config.yml) ]; then
+                            echo "The configuratio file you're deploying can't be the same as this build's confguration file"
+                            echo "Check the content of the configuratio file you're trying to deploy"
+                            exit 1
+                        fi
+            }
+
             BuildOrNot() {
-                        if [ "$SKIP" = true ]; then
+                        if [ "${SKIP}" = "true" ]; then
                             echo "As per your parameters, build will be skipped on target projects upon the configuration deployment"
                             echo ' export MESSAGE="Global config update [skip ci]" ' >> BASH_ENV
                          else
@@ -40,39 +49,40 @@ commands:
                         fi
             }
             
+            echo $SKIP
+            echo ${SKIP}
+
             CheckEnvVars
+            NotThisConfig
             BuildOrNot
             
       - run:
           name: Deploying configuration to targets
           environment:
-            CENTRAL_CONFIG: << parameters.config-to-deploy >>
-            TARGET_LIST: << parameters.targets-list >>
-            FORCE: << parameters.force-update >>
+            CENTRAL_CONFIG: "<<parameters.config-to-deploy>>"
+            TARGET_LIST: "<<parameters.targets-list>>"
+            FORCE: "<<parameters.force-update>>"
           command: |
-            echo 'export GLOBAL_64="$(cat ${CENTRAL_CONFIG} | base64 -w 0)" ' >> $BASH_ENV
-            while read -r target
-              do
-                echo "export REPO=$(echo $target | awk -F', ' '{print $1}')" >> BASH_ENV
-                echo "export BRANCH=$(echo $target | awk -F', ' '{print $2}')" >> BASH_ENV
-                source BASH_ENV
-                echo $REPO
-                echo $BRANCH
-                
-                if [[ $(curl -s -w '%{response_code}' --output /dev/null --location --request GET "https://api.github.com/repos/$REPO/contents/.circleci/config.yml?ref=$BRANCH" --header "Authorization: token $GH_TOKEN" --header "Accept: application/vnd.github.v3+json") == 404 ]];
-                  then
-                    curl -X PUT https://api.github.com/repos/$REPO/contents/.circleci/config.yml -H "Authorization: token $GH_TOKEN" -H 'Accept: application/vnd.github.v3+json' -d '{"message":"'"$MESSAGE"'","content":"'"$GLOBAL_64"'","branch":"'"${BRANCH}"'"}'
-                  else
-                    echo 'export BLOB_SHA=$(curl --location --request GET "https://api.github.com/repos/${REPO}/contents/.circleci/config.yml?ref=${BRANCH}" --header "Authorization: token ${GH_TOKEN}" --header "Accept: application/vnd.github.v3+json"|jq -r .sha)' >> $BASH_ENV
-                    source $BASH_ENV
-                      if [[ $(git hash-object global-ci.yml) != $BLOB_SHA ]] || [[ ${FORCE} ]];
-                        then
-                          curl -X PUT https://api.github.com/repos/$REPO/contents/.circleci/config.yml --header "Authorization: token ${GH_TOKEN}" --header "Accept: application/vnd.github.v3+json" --data-raw '{"message":"'"$MESSAGE"'","content":"'"${GLOBAL_64}"'","sha": "'"$BLOB_SHA"'","branch":"'"$BRANCH"'"}'
-                        else
-                          echo "Not pushing same version of the config file"
-                      fi
-                fi  
-              done < ${TARGET_LIST}
+            DeployConf() {
+                        GLOBAL_64="$(cat "${CENTRAL_CONFIG}" | base64 -w 0)"
+                        while read -r target
+                          do
+                            REPO=$(echo $target | awk -F', ' '{print $1}')
+                            BRANCH=$(echo $target | awk -F', ' '{print $2}')
+                            if [ "$(curl -s -w '%{response_code}' --output /dev/null --location --request GET "https://api.github.com/repos/$REPO/contents/.circleci/config.yml?ref=$BRANCH" --header "Authorization: token $GH_TOKEN" --header "Accept: application/vnd.github.v3+json")" = "404" ]; then
+                              curl -X PUT https://api.github.com/repos/$REPO/contents/.circleci/config.yml -H "Authorization: token $GH_TOKEN" -H 'Accept: application/vnd.github.v3+json' -d '{"message":"'"$MESSAGE"'","content":"'"$GLOBAL_64"'","branch":"'"${BRANCH}"'"}'
+                            else
+                              BLOB_SHA=$(curl --location --request GET "https://api.github.com/repos/${REPO}/contents/.circleci/config.yml?ref=${BRANCH}" --header "Authorization: token ${GH_TOKEN}" --header "Accept: application/vnd.github.v3+json"|jq -r .sha)
+                              if [ ! "$(git hash-object "${CENTRAL_CONFIG}")" = "$BLOB_SHA" ] || [ "${FORCE}" = "true" ]; then
+                                curl -X PUT https://api.github.com/repos/$REPO/contents/.circleci/config.yml --header "Authorization: token ${GH_TOKEN}" --header "Accept: application/vnd.github.v3+json" --data-raw '{"message":"'"$MESSAGE"'","content":"'"${GLOBAL_64}"'","sha": "'"$BLOB_SHA"'","branch":"'"$BRANCH"'"}'
+                              else
+                                echo "Not pushing same version of the config file"
+                              fi
+                            fi  
+                          done < ${TARGET_LIST}
+            }
+            
+            DeployConf
 jobs:
   # config-validation:
   #   parameters:
